sudo: required
dist: trusty

language: node_js

node_js:
  - "6"

cache:
  bundler: true
  directories:
    - node_modules

before_install: if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi

before_script:

script:

branches:
  only:
    - "master"
