sudo: required
dist: trusty

language: node_js

node_js:
  - "6"

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

before_install:

before_script:

script:

branches:
  only:
    - "master"
    - /^greenkeeper-.*$/
